- name: Ensure ansible and git are installed
  apt:
    name:
      - ansible
      - git
      - acl
    state: present

- name: Create ansible user
  user:
    name: ansible
    shell: /bin/bash
    create_home: yes
    expires: -1

- name: Create the required directories if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ansible
    group: ansible
    mode: '0755'
  loop:
    - /etc/ansible
    - /data/ansible
    - /etc/ansible/roles
    - /etc/ansible/inventories
    - /home/ansible/.ssh

- name: Create the SSH directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'
  loop:
    - /home/ansible/.ssh
